# Site settings
title:            Lei Shi's Blog
subtitle:         Example Blog
description:      This is the jekyllTheme example blog. It only exists to demonstrate how the theme looks and feels.
keywords:         demo theme example github jekyll features
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "" # the subpath of your site, e.g. /blog
url:              "https://blog.leishi.io" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /pages/:categories/:title
cover:            /assets/machu-picchu.jpg
disqus_shortname: "blog"

# Google Analytics 
google-analytics: 'UA-119177383-3'

author:
  initial:      lei
  name:         "Lei Shi"
  picture:      /assets/profile.jpg
  bio:          Yet another software engineer
  location:     China
  email:        me@leishi.io
  github:       leishi1313


# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]
